{"version":3,"file":"internal-error.js","sourceRoot":"","sources":["../../../../../src/app/common/rest/errors/internal-error.ts"],"names":[],"mappings":";;;;;;;;;;;;AAAA,2CAAyC;AAEzC;IAAmC,iCAAS;IAE1C,uBACS,aAAoB,EACpB,OAAqD;QAArD,wBAAA,EAAA,6CAAqD;QAF9D,YAIE,kBAAM,OAAO,EAAE,GAAG,EAAE,gBAAgB,CAAC,SAEtC;QALQ,mBAAa,GAAb,aAAa,CAAO;QACpB,aAAO,GAAP,OAAO,CAA8C;QAG5D,KAAI,CAAC,IAAI,GAAG,eAAe,CAAC;;IAC9B,CAAC;IAEH,oBAAC;AAAD,CAAC,AAVD,CAAmC,sBAAS,GAU3C;AAVY,sCAAa","sourcesContent":["import { RestError } from './rest-error';\n\nexport class InternalError extends RestError {\n\n  constructor(\n    public originalError: Error,\n    public message: string = 'An unexpected error has occurred.'\n  ) {\n    super(message, 500, 'INTERNAL_ERROR');\n    this.name = 'InternalError';\n  }\n\n}\n"]}